### ISSUE TITLE
Conflicting packages

### ISSUE THREAD

**Issue by CentillionJinx** [anfreire/updateMe-Mobile#11]
I tried to update my existing modded application, in this case picsart, and I tried adGuard, and for both of which, it resulted in the following error as shown in the screenshot. I am running a beta version of android 15 (Pixel 7 p), maybe it could be affecting the installation process, although I doubt it does. Any idea how it can be resolved? 

![image](https://github.com/user-attachments/assets/4ac56d42-14db-47cb-829a-af2aec15f89c)

**Comment by anfreire** [comment]
Thank you for reporting this issue with updating your modded applications.

**Regarding the update process**:
The app scrapes the provider's website to detect new releases. This allows me to archive the latest versions for distribution and analyze them for potential security concerns. However, I've noticed that providers occasionally alter their publication sources, which can result in signature variations.

In light of this, I suggest experimenting with different providers to identify the most consistent source. This approach could potentially improve the stability of the update process and ensure more reliable signatures over time.
