### ISSUE TITLE
Instagram - Instander

### ISSUE THREAD

**Issue by wefalltomorrow** [anfreire/updateMe-Mobile#12]
How come Instander is the default option or even included? It's completely redundant compared to MyInsta and is very old/abandoned.

**Comment by TopperBG** [comment]
You are right but give a test to Honista - lovely app

**Comment by anfreire** [comment]
Thank you for your feedback on the Instagram mod options. I appreciate you bringing this to my attention.

You make a good point about Instander's current status. Based on your suggestion, I will update the app to set MyInsta as the first option and have it selected by default. This change should better reflect the most current and actively maintained mod options available.

**Comment by Neeraj1221a** [comment]
Download karna hai
