### ISSUE TITLE
Multiple App versions

### ISSUE THREAD

**Issue by stepanzak** [anfreire/updateMe-Mobile#2]
Some apps, for example MyInsta, provide multiple versions of the app. Clone and Unclone in MyInsta's case. This app downloads only the Unclone version. It would be nice if the user could choose between thise versions.

Thanks for this cool app btw 🔥

**Comment by BabyOilJohnson** [comment]
Same, for instander the app downloads cloned version not the original ver.

**Comment by anfreire** [comment]
Done 🤌
