### ISSUE TITLE
Add root permission to install apps Backstage.

### ISSUE THREAD

**Issue by Fan-Bob** [anfreire/updateMe-Mobile#21]
Automatic background silent installation

**Comment by anfreire** [comment]
Thank you for your suggestion regarding automatic background silent installation. 

While this is an interesting feature idea, I won't be implementing it in the upcoming release.

The main reason for this decision is that such a feature would raise significant privacy and security concerns. Allowing an app to silently install other apps in the background without user interaction goes against best practices for user privacy and device security.

I aim to keep this app as transparent and user-controlled as possible, which means maintaining clear user oversight for all installation processes.

If you have any other feature suggestions that align with these privacy and security principles, please feel free to share them. I appreciate your input in helping improve the app!
