### ISSUE TITLE
Spotify Revanced

### ISSUE THREAD

**Issue by polnio** [anfreire/updateMe-Mobile#22]
First of all, thanks for this app, it is very convenient. 

I found many Revanced apps in this app, but it seems that it misses Spotify. I found it on this app, but from other sources. However I found it on the rootless Revanced Manager. Is there any reason?

**Comment by polnio** [comment]
Btw it seems that Duolingo Revanced is missing too, maybe related?

**Comment by anfreire** [comment]
@polnio Thanks for your feedback and for using the app!

**Regarding Spotify:**
The official ReVanced patches for Spotify only hide the premium navbar and apply a custom theme. I've decided not to include it since these patches don't offer significant functionality changes like ad removal or on-demand playback.

**As for Duolingo:**
There are currently no official ReVanced patches for Duolingo. You can check the official list of available patches at https://revanced.app/patches.

**Comment by polnio** [comment]
Ok, make sense. I'm a bit surprised about Duolingo, but I guess I'm missing something on how the rootless Revanced Manager app works. Thanks for your reply!

**Comment by Felitendo** [comment]
> @polnio Thanks for your feedback and for using the app!
> 
> **Regarding Spotify:** The official ReVanced patches for Spotify only hide the premium navbar and apply a custom theme. I've decided not to include it since these patches don't offer significant functionality changes like ad removal or on-demand playback.
> 
> **As for Duolingo:** There are currently no official ReVanced patches for Duolingo. You can check the official list of available patches at https://revanced.app/patches.

But what about Liteapks for Spotify?

**Comment by anfreire** [comment]
> > @polnio Thanks for your feedback and for using the app!
> > **Regarding Spotify:** The official ReVanced patches for Spotify only hide the premium navbar and apply a custom theme. I've decided not to include it since these patches don't offer significant functionality changes like ad removal or on-demand playback.
> > **As for Duolingo:** There are currently no official ReVanced patches for Duolingo. You can check the official list of available patches at https://revanced.app/patches.
> 
> But what about Liteapks for Spotify?

https://github.com/anfreire/updateMe-Data/blob/d2b90e5fdab359b863635b12e855585121cdfe88/index.json#L288

**Comment by Felitendo** [comment]
> > > @polnio Thanks for your feedback and for using the app!
> > > **Regarding Spotify:** The official ReVanced patches for Spotify only hide the premium navbar and apply a custom theme. I've decided not to include it since these patches don't offer significant functionality changes like ad removal or on-demand playback.
> > > **As for Duolingo:** There are currently no official ReVanced patches for Duolingo. You can check the official list of available patches at https://revanced.app/patches.
> > 
> > 
> > But what about Liteapks for Spotify?
> 
> https://github.com/anfreire/updateMe-Data/blob/d2b90e5fdab359b863635b12e855585121cdfe88/index.json#L288

Oh sorry I meant SoundCloud
