### ISSUE TITLE
Feature Request: Automatic App Updates

### ISSUE THREAD

**Issue by OmarNazzal150** [anfreire/updateMe-Mobile#29]
Dear Developer,
I am writing to suggest that you add the ability to automatically update apps to your Update Me app. This would be a very useful feature for users who want to keep their apps up-to-date without having to manually check for updates.
I believe that this feature would be a great addition to your app and would make it even more valuable to users. Thank you for your time and consideration.
Sincerely,

**Comment by HyrulianZer0** [comment]
I can get behind this, wont matter if the source changes, as long as its verified secure from VT ... Should be easy to implement ( in theory )

**Comment by anfreire** [comment]
I appreciate your input and the time you've taken to share this idea.

The issues #21 and #26 are related to this suggestion.

Here's where we stand:

1. Code Refactoring: I've just completed refactoring the codebase, which sets a good foundation for new feature implementations.

2. Contributing Guidelines: I'm in the process of creating a contributing.md file. This will help streamline the process of implementing new feature requests, potentially making additions like this one faster to implement.

3. Security Considerations: I'm open to adding an automatic update feature as long as it doesn't require any security bypasses or root access. User security is a top priority.

4. Further Investigation: I'll need to investigate further to determine the feasibility of including this feature in the upcoming release. There are technical and security aspects to consider.

**Comment by anfreire** [comment]
Closing this issue as duplicated.

The follow-up process will be available on issue #26.
