### ISSUE TITLE
Watsap

### ISSUE THREAD

**Issue by Mrperfect2267** [anfreire/updateMe-Mobile#38]

**Comment by anfreire** [comment]
Thank you for your interest in WhatsApp for our app. I appreciate you taking the time to reach out about this.

First, I'd like to remind all users that app suggestions should be made through the dedicated section within the app itself. This helps us keep track of user requests more efficiently.


Regarding WhatsApp specifically:

I've noticed the high number of users suggesting WhatsApp, and I understand its popularity. However, I've made the decision not to include it in our app for several important reasons:

1. Trusted Mods: I haven't been able to find a WhatsApp mod that I can confidently trust and verify as safe for our users.

2. Ban Risks: There have been alarming reports of users being banned from WhatsApp for using modded versions. This poses a significant risk to our users' accounts and communication.


Given these risks, I don't believe it's worth potentially jeopardizing our users' WhatsApp accounts or personal data.
