### ISSUE TITLE
Not downloading anything

### ISSUE THREAD

**Issue by JustABlitz** [anfreire/updateMe-Mobile#42]
Clicking any download button displays "Download unsuccessful" after a while (time frames ive experienced are between 10s and 1h between clicking button and getting notification)

> Android 14
> crDroid OS (LineageOS fork)
> Xiaomi Redmi Note 10 Pro
> Latest GitHub release of UpdateMe

**Comment by anfreire** [comment]
The error might be related to storage permissions or network connection issues. However, I won't be implementing fixes for the current version as I'm rebuilding UpdateMe 3.0.0 from scratch.

The new version will target Android 10 and above, allowing me to focus development on modern Android features and prevent these types of issues. This decision will help provide a more stable and reliable experience.

For now, you can try:
- Checking your storage permissions
- Verifying your network connection
- Clearing the app cache

Stay tuned for the official announcement about v3.0.0 which will include significant improvements to the app's stability and performance.
