### ISSUE TITLE
Not updating when Version isn't changing

### ISSUE THREAD

**Issue by Felitendo** [anfreire/updateMe-Mobile#45]
With the Ravanced Mods for example YouTube, I have the problem that it stays mostly on the same version so it's easier for Developers to add patches. But updateMe-Mobile only updates Apps when the version changes which isn't true for YouTube Revanced because it has mostly stayed on the same version BUT it HAS been updated

**Comment by Felitendo** [comment]
TLDR: As long as Patches get developed for YouTube on Version 19.16.39, updateMe-Mobile will not update the App with the patches because the version (19.16.39) stays the same

**Comment by anfreire** [comment]
The current version only checks version numbers for updates, which doesn't catch modified APKs that maintain the same version number. However, I won't be implementing fixes for the current version as I'm rebuilding UpdateMe 3.0.0 from scratch.

The new version will include SHA256 hash monitoring of installed APKs, allowing it to detect updates even when the version number remains the same. This means it will catch all updates to modified apps like Revanced, regardless of their version numbering strategy.

Stay tuned for the official announcement about v3.0.0 which will include this and many other improvements to make update detection more reliable.
