### ISSUE TITLE
I can't download any apk in mobile due to android 13

### ISSUE THREAD

**Issue by Sultan4427** [anfreire/updateMe-Mobile#46]
Help me to download apks in my mobile

**Comment by Nihal098765** [comment]
How to download

**Comment by Dinesh3126** [comment]
How to download

**Comment by anfreire** [comment]
The download issues on Android 13 are related to the stricter storage permission model. However, I won't be implementing fixes for the current version as I'm rebuilding UpdateMe 3.0.0 from scratch.

The new version will target Android 10 and above, with specific optimizations for Android 13's permission system. This will provide a more stable experience and better handle modern Android security features.

For now, you can try:
- Granting storage permissions manually in Settings > Apps > UpdateMe > Permissions
- Clearing the app cache
- Reinstalling the app if permissions aren't showing up

Stay tuned for the official announcement about v3.0.0 which will include significant improvements to the app's permission handling and overall stability.
