### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by techtanic** [anfreire/updateMe-Mobile#47]
Hey, sorry about making an issue but wanted to let you know I have emailed you regarding UpdateMe.
An acknowledgement would be appreciated.

**Comment by Felitendo** [comment]
I have also contacted him last week. I think he's dead or something

**Comment by Felitendo** [comment]
He has made contributions in private repositorys though

**Comment by aery193** [comment]
HELLO

**Comment by anfreire** [comment]
Closing this issue.

Please note that my personal email and contacts are not the appropriate channels for reporting bugs or suggesting features for UpdateMe. All UpdateMe-related discussions should happen here through GitHub issues to maintain transparency and keep all project-related communications in one place.

I won't be responding to UpdateMe-related emails. Please use GitHub issues for any app-related communications.
