### ISSUE TITLE
Reddit stops working after every reboot

### ISSUE THREAD

**Issue by Damglador** [anfreire/updateMe-Mobile#49]
![Screenshot_20241004-143105.png](https://github.com/user-attachments/assets/1f531784-c6aa-4ece-8d40-db6f3b6a0811)

I install Reddit Revanced Extended, because Revanced marked as not secure, and every time I reboot it stops working, if I try to open it, it crashes and the app name is broken as shown on the screenshot above

**Comment by anfreire** [comment]
Closing this issue as invalid.

The app crashing after reboot and the broken app name are issues with the modified Reddit app provided by the provider, not with UpdateMe itself. UpdateMe is only responsible for downloading and installing the APK file - any functionality issues or bugs within the modified apps themselves are related to how the provider modified the app.

If you're experiencing issues with this specific mod, you might want to try a different mod version or provider.
