### ISSUE TITLE
Brilliant doesn't work

### ISSUE THREAD

**Issue by jano5757** [anfreire/updateMe-Mobile#51]
Download it from update me and when I want to start a course it tells me "unable to connect to brilliant at the momen"

**Comment by Louis-htmlcss** [comment]
Brilliant mod not working. Please close this issue

**Comment by anfreire** [comment]
Closing this issue as invalid.

The error message "unable to connect to brilliant at the moment" is coming from the modified Brilliant app itself, not from UpdateMe. UpdateMe is only responsible for providing and installing the APK file. Any functionality issues, connection problems, or missing features within the modified apps are related to the specific mod version provided by the modder/provider, not to UpdateMe itself.

If you're experiencing issues with a modified app, you may want to try a different mod version or provider.
