### ISSUE TITLE
I want to suggest you my app

### ISSUE THREAD

**Issue by salmanmemon7** [anfreire/updateMe-Mobile#60]
Instafusion is a project made to provide latest Instagram alpha with Developer Options enabled And Ads Free Experience And IOS Emojis .
t.me/instafusions

**Comment by Dheerajjaat1802** [comment]
Disney plus hotstar

**Comment by anfreire** [comment]
Closing this issue.

I'm not adding new app sources to the current version of UpdateMe. However, in the upcoming v3.0.0, users will be able to create and share their own providers, making it possible to track updates from various sources like this.

Stay tuned for the official announcement about v3.0.0 which will include more details about the new provider system.
