### ISSUE TITLE
URL add API set-up like Obtainium

### ISSUE THREAD

**Issue by coolswapnil** [anfreire/updateMe-Mobile#61]
Hello, 
 Can you setup api like Obtainium app where we can browse and add URL of modded app from supported sires and Update Me will track them for updates and notify when it is available.
This will help greatly for all the user's.
There will be no need to raise App Request also users can selectively add the which they use and wants to keep them updated

**Comment by WhoMI7** [comment]
This is far better than request system

**Comment by anfreire** [comment]
Closing this issue.

While this is a good suggestion, I'm not adding any new app sources to the current version. However, I'm excited to share that this type of functionality will be available in v3.0.0.

The new version will introduce a system where users can create and share their own providers, giving everyone more flexibility in choosing their app sources and managing updates. This will be part of the complete rebuild that's currently in development.

Stay tuned for the official announcement about v3.0.0 which will include more details about this feature.

**Comment by coolswapnil** [comment]
That's great 👍. Thank you so much.

This will help so much and with security scan (VirusTotal) we will have great idea which app is safe and which is not.
