### ISSUE TITLE
Wrong apps

### ISSUE THREAD

**Issue by sankhababu** [anfreire/updateMe-Mobile#7]
Express vpn and Nord vpn as available with this app is completely pretending.

These are both same and actually moded Ultrasurf vpn.

I didn't check any other app but respected dev should be more careful about such instances.

Otherwise, his honest hard labor will turn into malware supply.

**Comment by OR555** [comment]
I suggest for the time being to mark the VPN category as unsafe mods in the risk taker.

**Comment by anfreire** [comment]
Thanks for bringing this to my attention.
I will solve this this weekend.

**Comment by anfreire** [comment]
**I have temporarily removed all VPNs and will only add them back once we can ensure they are from more trustworthy providers.**

@sankhababu 
To clarify, the apps are added automatically through web scraping from sources like MODYOLO, LITEAPKS, and APKDONE. My role is to initiate this automated process, which means apps from these sources are included without manual vetting.

@OR555 
Regarding app security, the system marks an app as unsafe if any tests on VirusTotal flag it for malware. This process is also automated to ensure unbiased and consistent evaluation.
