### ISSUE TITLE
Development abandoned? 

### ISSUE THREAD

**Issue by oroboros** [anfreire/updateMe-Mobile#76]
It's a been a few months since we've heard from dev, has development been abandoned?

**Comment by luca7185** [comment]
Also, the issues section needs a cleanup. It's full of spam.

**Comment by pective** [comment]
there are some commits being made i see, but no announcements or anything

**Comment by SleepDaemon** [comment]
> Also, the issues section needs a cleanup. It's full of spam.

All of them are from the dev itself lol

**Comment by anfreire** [comment]
No, development hasn't been abandoned! I've been occupied lately but I want to share some exciting news:

I'm currently rebuilding UpdateMe from scratch with a completely new architecture. This new version will:
- Support community-made providers, allowing for more app sources
- Provide a richer user experience
- Have a more robust and maintainable codebase

I'll be making an official announcement soon with detailed information about:
- The new architecture and vision
- How the community can contribute
- Planned features and improvements
- Development roadmap

As for the issues section - yes, I'm aware it needs cleanup and I'm actively working on organizing and addressing the spam.

Thank you for your patience and continued interest in UpdateMe. This project has great potential and I'm looking forward to collaborating with the community to make it even better.

**Comment by mitch030504** [comment]
> No, development hasn't been abandoned! I've been occupied lately but I want to share some exciting news:
> 
> I'm currently rebuilding UpdateMe from scratch with a completely new architecture. This new version will:
> 
>     * Support community-made providers, allowing for more app sources
> 
>     * Provide a richer user experience
> 
>     * Have a more robust and maintainable codebase
> 
> 
> I'll be making an official announcement soon with detailed information about:
> 
>     * The new architecture and vision
> 
>     * How the community can contribute
> 
>     * Planned features and improvements
> 
>     * Development roadmap
> 
> 
> As for the issues section - yes, I'm aware it needs cleanup and I'm actively working on organizing and addressing the spam.
> 
> Thank you for your patience and continued interest in UpdateMe. This project has great potential and I'm looking forward to collaborating with the community to make it even better.

Are you by any chance still working on this?
