### ISSUE TITLE
[APP REQUEST] CV Engineer | Resume builder

### ISSUE THREAD

**Issue by Ironfist69** [anfreire/updateMe-Mobile#77]
Need this app named **CV Engineer**

https://play.google.com/store/apps/details?id=sampson.cvbuilder

**Comment by anfreire** [comment]
Closing this issue.

App suggestions are no longer accepted through GitHub issues. The template for suggesting apps has been removed from the issues section.

The issues section is now focused solely on reporting bugs and technical problems with UpdateMe itself.
