### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sudiptakayal12** [anfreire/updateMe-Mobile#79]
## Steps to Reproduce

1. 
2. 
3. 

## Device Information

- Device Model: 
- Android Version: 
- App Version: 

## Error Log

```
Paste your logs here
```

## Checklist

- [ ] I have checked for similar issues
- [ ] I am using the latest version of the app
- [ ] I can consistently reproduce this issue
- [ ] I have included all the required information above

## Related Permissions

- [x] Internet
- [ ] Access Network State
- [x] Install Packages
- [x] Delete Packages
- [x] Query Packages
- [x] Notifications
- [ ] Boot Completed

**Comment by pective** [comment]
i agree
